# Generated by Django 4.1 on 2022-08-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_podcast', '0006_podcasts_description_podcasts_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcasts',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
